version: "3.1"
language: "en"
pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 50
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50
- name: FallbackClassifier
  threshold: 0.75
  ambiguity_threshold: 0.0
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  epochs: 50
assistant_id: 20260208-135131-ash-upstream

# Enable debug logging
logging:
  level: DEBUG
